"""Spanish verb data and irregular conjugations.

This module contains:
- Lists of irregular and regular verbs
- Complete conjugation tables for irregular verbs across all tenses
- Person definitions for simplified Spanish (6 persons)
"""

# Lists of verbs
IRREGULAR_VERBS = [
    "ir",
    "ser",
    "estar",
    "hacer",
    "poder",
    "haber",
    "tener",
    "querer",
    "saber",
]
REGULAR_VERBS = ["deber"]  # Can add more regular -er verbs here
ALL_VERBS = IRREGULAR_VERBS + REGULAR_VERBS

# Tenses
TENSES = ["present", "preterite", "imperfect", "future", "conditional"]

# Person definitions (simplified + Ustedes)
PERSONS = ["Yo", "Tú", "Él/Ella", "Nosotros", "Ellos", "Ustedes"]

# Irregular conjugation overrides for all 9 irregular verbs
# Structure: IRREGULAR_OVERRIDES[verb][tense][person] = conjugated_form
IRREGULAR_OVERRIDES = {
    "ir": {
        "present": {
            "Yo": "voy",
            "Tú": "vas",
            "Él/Ella": "va",
            "Nosotros": "vamos",
            "Ellos": "van",
            "Ustedes": "van",
        },
        "preterite": {
            "Yo": "fui",
            "Tú": "fuiste",
            "Él/Ella": "fue",
            "Nosotros": "fuimos",
            "Ellos": "fueron",
            "Ustedes": "fueron",
        },
        "imperfect": {
            "Yo": "iba",
            "Tú": "ibas",
            "Él/Ella": "iba",
            "Nosotros": "íbamos",
            "Ellos": "iban",
            "Ustedes": "iban",
        },
        "future": {
            "Yo": "iré",
            "Tú": "irás",
            "Él/Ella": "irá",
            "Nosotros": "iremos",
            "Ellos": "irán",
            "Ustedes": "irán",
        },
        "conditional": {
            "Yo": "iría",
            "Tú": "irías",
            "Él/Ella": "iría",
            "Nosotros": "iríamos",
            "Ellos": "irían",
            "Ustedes": "irían",
        },
    },
    "ser": {
        "present": {
            "Yo": "soy",
            "Tú": "eres",
            "Él/Ella": "es",
            "Nosotros": "somos",
            "Ellos": "son",
            "Ustedes": "son",
        },
        "preterite": {
            "Yo": "fui",
            "Tú": "fuiste",
            "Él/Ella": "fue",
            "Nosotros": "fuimos",
            "Ellos": "fueron",
            "Ustedes": "fueron",
        },
        "imperfect": {
            "Yo": "era",
            "Tú": "eras",
            "Él/Ella": "era",
            "Nosotros": "éramos",
            "Ellos": "eran",
            "Ustedes": "eran",
        },
        "future": {
            "Yo": "seré",
            "Tú": "serás",
            "Él/Ella": "será",
            "Nosotros": "seremos",
            "Ellos": "serán",
            "Ustedes": "serán",
        },
        "conditional": {
            "Yo": "sería",
            "Tú": "serías",
            "Él/Ella": "sería",
            "Nosotros": "seríamos",
            "Ellos": "serían",
            "Ustedes": "serían",
        },
    },
    "estar": {
        "present": {
            "Yo": "estoy",
            "Tú": "estás",
            "Él/Ella": "está",
            "Nosotros": "estamos",
            "Ellos": "están",
            "Ustedes": "están",
        },
        "preterite": {
            "Yo": "estuve",
            "Tú": "estuviste",
            "Él/Ella": "estuvo",
            "Nosotros": "estuvimos",
            "Ellos": "estuvieron",
            "Ustedes": "estuvieron",
        },
        "imperfect": {
            "Yo": "estaba",
            "Tú": "estabas",
            "Él/Ella": "estaba",
            "Nosotros": "estábamos",
            "Ellos": "estaban",
            "Ustedes": "estaban",
        },
        "future": {
            "Yo": "estaré",
            "Tú": "estarás",
            "Él/Ella": "estará",
            "Nosotros": "estaremos",
            "Ellos": "estarán",
            "Ustedes": "estarán",
        },
        "conditional": {
            "Yo": "estaría",
            "Tú": "estarías",
            "Él/Ella": "estaría",
            "Nosotros": "estaríamos",
            "Ellos": "estarían",
            "Ustedes": "estarían",
        },
    },
    "hacer": {
        "present": {
            "Yo": "hago",
            "Tú": "haces",
            "Él/Ella": "hace",
            "Nosotros": "hacemos",
            "Ellos": "hacen",
            "Ustedes": "hacen",
        },
        "preterite": {
            "Yo": "hice",
            "Tú": "hiciste",
            "Él/Ella": "hizo",
            "Nosotros": "hicimos",
            "Ellos": "hicieron",
            "Ustedes": "hicieron",
        },
        "imperfect": {
            "Yo": "hacía",
            "Tú": "hacías",
            "Él/Ella": "hacía",
            "Nosotros": "hacíamos",
            "Ellos": "hacían",
            "Ustedes": "hacían",
        },
        "future": {
            "Yo": "haré",
            "Tú": "harás",
            "Él/Ella": "hará",
            "Nosotros": "haremos",
            "Ellos": "harán",
            "Ustedes": "harán",
        },
        "conditional": {
            "Yo": "haría",
            "Tú": "harías",
            "Él/Ella": "haría",
            "Nosotros": "haríamos",
            "Ellos": "harían",
            "Ustedes": "harían",
        },
    },
    "poder": {
        "present": {
            "Yo": "puedo",
            "Tú": "puedes",
            "Él/Ella": "puede",
            "Nosotros": "podemos",
            "Ellos": "pueden",
            "Ustedes": "pueden",
        },
        "preterite": {
            "Yo": "pude",
            "Tú": "pudiste",
            "Él/Ella": "pudo",
            "Nosotros": "pudimos",
            "Ellos": "pudieron",
            "Ustedes": "pudieron",
        },
        "imperfect": {
            "Yo": "podía",
            "Tú": "podías",
            "Él/Ella": "podía",
            "Nosotros": "podíamos",
            "Ellos": "podían",
            "Ustedes": "podían",
        },
        "future": {
            "Yo": "podré",
            "Tú": "podrás",
            "Él/Ella": "podrá",
            "Nosotros": "podremos",
            "Ellos": "podrán",
            "Ustedes": "podrán",
        },
        "conditional": {
            "Yo": "podría",
            "Tú": "podrías",
            "Él/Ella": "podría",
            "Nosotros": "podríamos",
            "Ellos": "podrían",
            "Ustedes": "podrían",
        },
    },
    "haber": {
        "present": {
            "Yo": "he",
            "Tú": "has",
            "Él/Ella": "ha",
            "Nosotros": "hemos",
            "Ellos": "han",
            "Ustedes": "han",
        },
        "preterite": {
            "Yo": "hube",
            "Tú": "hubiste",
            "Él/Ella": "hubo",
            "Nosotros": "hubimos",
            "Ellos": "hubieron",
            "Ustedes": "hubieron",
        },
        "imperfect": {
            "Yo": "había",
            "Tú": "habías",
            "Él/Ella": "había",
            "Nosotros": "habíamos",
            "Ellos": "habían",
            "Ustedes": "habían",
        },
        "future": {
            "Yo": "habré",
            "Tú": "habrás",
            "Él/Ella": "habrá",
            "Nosotros": "habremos",
            "Ellos": "habrán",
            "Ustedes": "habrán",
        },
        "conditional": {
            "Yo": "habría",
            "Tú": "habrías",
            "Él/Ella": "habría",
            "Nosotros": "habríamos",
            "Ellos": "habrían",
            "Ustedes": "habrían",
        },
    },
    "tener": {
        "present": {
            "Yo": "tengo",
            "Tú": "tienes",
            "Él/Ella": "tiene",
            "Nosotros": "tenemos",
            "Ellos": "tienen",
            "Ustedes": "tienen",
        },
        "preterite": {
            "Yo": "tuve",
            "Tú": "tuviste",
            "Él/Ella": "tuvo",
            "Nosotros": "tuvimos",
            "Ellos": "tuvieron",
            "Ustedes": "tuvieron",
        },
        "imperfect": {
            "Yo": "tenía",
            "Tú": "tenías",
            "Él/Ella": "tenía",
            "Nosotros": "teníamos",
            "Ellos": "tenían",
            "Ustedes": "tenían",
        },
        "future": {
            "Yo": "tendré",
            "Tú": "tendrás",
            "Él/Ella": "tendrá",
            "Nosotros": "tendremos",
            "Ellos": "tendrán",
            "Ustedes": "tendrán",
        },
        "conditional": {
            "Yo": "tendría",
            "Tú": "tendrías",
            "Él/Ella": "tendría",
            "Nosotros": "tendríamos",
            "Ellos": "tendrían",
            "Ustedes": "tendrían",
        },
    },
    "querer": {
        "present": {
            "Yo": "quiero",
            "Tú": "quieres",
            "Él/Ella": "quiere",
            "Nosotros": "queremos",
            "Ellos": "quieren",
            "Ustedes": "quieren",
        },
        "preterite": {
            "Yo": "quise",
            "Tú": "quisiste",
            "Él/Ella": "quiso",
            "Nosotros": "quisimos",
            "Ellos": "quisieron",
            "Ustedes": "quisieron",
        },
        "imperfect": {
            "Yo": "quería",
            "Tú": "querías",
            "Él/Ella": "quería",
            "Nosotros": "queríamos",
            "Ellos": "querían",
            "Ustedes": "querían",
        },
        "future": {
            "Yo": "querré",
            "Tú": "querrás",
            "Él/Ella": "querrá",
            "Nosotros": "querremos",
            "Ellos": "querrán",
            "Ustedes": "querrán",
        },
        "conditional": {
            "Yo": "querría",
            "Tú": "querrías",
            "Él/Ella": "querría",
            "Nosotros": "querríamos",
            "Ellos": "querrían",
            "Ustedes": "querrían",
        },
    },
    "saber": {
        "present": {
            "Yo": "sé",
            "Tú": "sabes",
            "Él/Ella": "sabe",
            "Nosotros": "sabemos",
            "Ellos": "saben",
            "Ustedes": "saben",
        },
        "preterite": {
            "Yo": "supe",
            "Tú": "supiste",
            "Él/Ella": "supo",
            "Nosotros": "supimos",
            "Ellos": "supieron",
            "Ustedes": "supieron",
        },
        "imperfect": {
            "Yo": "sabía",
            "Tú": "sabías",
            "Él/Ella": "sabía",
            "Nosotros": "sabíamos",
            "Ellos": "sabían",
            "Ustedes": "sabían",
        },
        "future": {
            "Yo": "sabré",
            "Tú": "sabrás",
            "Él/Ella": "sabrá",
            "Nosotros": "sabremos",
            "Ellos": "sabrán",
            "Ustedes": "sabrán",
        },
        "conditional": {
            "Yo": "sabría",
            "Tú": "sabrías",
            "Él/Ella": "sabría",
            "Nosotros": "sabríamos",
            "Ellos": "sabrían",
            "Ustedes": "sabrían",
        },
    },
}

# Regular -er verb endings for each tense
# Note: All verbs in this project are -er verbs (deber, etc.)
REGULAR_ENDINGS_ER = {
    "present": {
        "Yo": "o",
        "Tú": "es",
        "Él/Ella": "e",
        "Nosotros": "emos",
        "Ellos": "en",
        "Ustedes": "en",
    },
    "preterite": {
        "Yo": "í",
        "Tú": "iste",
        "Él/Ella": "ió",
        "Nosotros": "imos",
        "Ellos": "ieron",
        "Ustedes": "ieron",
    },
    "imperfect": {
        "Yo": "ía",
        "Tú": "ías",
        "Él/Ella": "ía",
        "Nosotros": "íamos",
        "Ellos": "ían",
        "Ustedes": "ían",
    },
    "future": {
        "Yo": "é",
        "Tú": "ás",
        "Él/Ella": "á",
        "Nosotros": "emos",
        "Ellos": "án",
        "Ustedes": "án",
    },
    "conditional": {
        "Yo": "ía",
        "Tú": "ías",
        "Él/Ella": "ía",
        "Nosotros": "íamos",
        "Ellos": "ían",
        "Ustedes": "ían",
    },
}
